export type Brand<TValue, TBrand extends string> = TValue & {
  readonly __brand: TBrand;
};

export type { MossError, MossErrorClass } from "@moss/module-sdk/errors";

export * from "./app-map-core.js";
export * from "./schema-fragments.js";
export * from "./ai-api.js";
export * from "./ai-service-binding-api.js";
export * from "./ai-voice-api.js";
export * from "./ai-audit-api.js";
export * from "./ai-summary-api.js";
export * from "./briefings-api.js";
export * from "./briefing-action-rows.js";
export * from "./calendar-briefing-settings-api.js";
export * from "./calendar-api.js";
export * from "./chat-api.js";
export * from "./chat-archive-api.js";
export * from "./chat-settings-api.js";
export * from "./chat-skills-api.js";
export * from "./connectors-api.js";
export * from "./imap-providers.js";
export * from "./email-api.js";
export * from "./email-briefing-settings-api.js";
export * from "./notifications-api.js";
export * from "./tasks-api.js";
export * from "./tasks-view.js";
export * from "./wellness-api.js";
export * from "./workflows-api.js";
export * from "./onboarding-api.js";
export * from "./platform-api.js";
export * from "./me-api.js";
export * from "./persona-api.js";
export * from "./source-behaviors-api.js";
export * from "./env.js";
export * from "./settings-api.js";
export * from "./themes-api.js";
export * from "./sports-api.js";
export * from "./sports-standings-preferences-api.js";
export * from "./sports-sources-api.js";
export * from "./news-api.js";
export * from "./news-credentials-api.js";
export * from "./weather-api.js";
export * from "./web-search-api.js";
export * from "./runtime-config-api.js";
export * from "./yolo-api.js";
export * from "./notes-api.js";
export * from "./integrations-api.js";
export * from "./workshop-api.js";
export * from "./priority-model-api.js";
export * from "./memory-graph-api.js";
export * from "./usefulness-feedback-api.js";
export * from "./story-relevance.js";
export * from "./memory-dashboard-api.js";
export * from "./proactive-monitoring-api.js";
export * from "./freshness-types.js";
export * from "./time.js";
export * from "./recurring-schedule.js";
export * from "./briefings-format.js";
